linters:
  enable-all: true
  disable:
    - gofumpt
    - depguard
    - wsl
    - wrapcheck
    - exhaustruct
    - execinquery
    - gomnd
    - varnamelen
    - godox
    - exportloopref
    - mnd # Too much bit magic in this project.

linters-settings:
  cyclop:
    max-complexity: 15
